version: "1.0"

services:
  app:
    container_name: react-github-gql
    image: react-github-gql
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000